name: Build release

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm link packages/pontem-providers
      - run: yarn
      - run: yarn setup
      - run: yarn dist